# Generated by Django 3.1.3 on 2021-02-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL_RESIEVED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RecievedAdress', models.URLField(unique=True)),
                ('ShortAdress', models.URLField(blank=True, null=True)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
