# Generated by Django 3.1.1 on 2021-02-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlReciever', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_resieved',
            name='RecievedAdress',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
