# Generated by Django 3.1.1 on 2021-02-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlReciever', '0002_auto_20210220_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='url_resieved',
            name='csrftoken',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
