# Generated by Django 3.1.1 on 2021-02-20 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlReciever', '0004_auto_20210220_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_resieved',
            name='ShortAdress',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
