# Generated by Django 3.1.1 on 2021-02-20 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlReciever', '0005_auto_20210220_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_resieved',
            name='RecievedAdress',
            field=models.CharField(max_length=300),
        ),
    ]
