# Generated by Django 3.1.1 on 2021-02-20 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlReciever', '0006_auto_20210220_0414'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='URL_RESIEVED',
            new_name='URL_RECIEVED',
        ),
    ]
