# Generated by Django 3.1.1 on 2021-02-20 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlReciever', '0008_remove_url_recieved_csrftoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url_recieved',
            old_name='ShortAdress',
            new_name='ShortAdressInt',
        ),
    ]
