# Generated by Django 3.1.5 on 2021-02-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlReciever', '0009_auto_20210220_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='url_recieved',
            name='qr',
            field=models.ImageField(blank=True, upload_to='', verbose_name='/qrs/q'),
        ),
    ]
