# Generated by Django 3.1.5 on 2021-02-21 04:02

from django.db import migrations, models
import urlReciever.utils


class Migration(migrations.Migration):

    dependencies = [
        ('urlReciever', '0011_auto_20210221_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_recieved',
            name='qr',
            field=models.ImageField(blank=True, upload_to=urlReciever.utils.media_upload_path),
        ),
    ]
